FROM tiangolo/uwsgi-nginx-flask:python3.8-alpine

COPY ./requirements.txt /requirements.txt

RUN \
 apk add --no-cache postgresql-libs postgresql postgresql-contrib && \
 apk add --no-cache --virtual .build-deps gcc musl-dev postgresql-dev && \
 python3 -m pip install -r /requirements.txt --no-cache-dir

USER postgres:postgres

COPY ./tests /tests
COPY ./app /app

RUN python3 -m pytest /tests/ -rP -v

USER root
